---
- hosts: "blossom"
  become: "yes"
  roles:
    - "City-of-Bloomington.php"
    - "City-of-Bloomington.mysql"

  tasks:
    - name: "Install php and related packages"
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: "present"
      vars:
        packages:
        - "php-mysql"

    - name: "Create mysql database"
      community.mysql.mysql_db:
        config_file: "{{ mysql_defaults_extra_file }}"
        name: "{{ blossom_db.default.name }}"
        state: "present"

    - name: "Create mysql user for site"
      community.mysql.mysql_user:
        name:     "{{ blossom_db.default.user }}"
        password: "{{ blossom_db.default.pass }}"
        priv:     "{{ blossom_db.default.name }}.*:ALL"
        state: "present"
        config_file: "{{ mysql_defaults_extra_file }}"

    - name: "Create directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
        mode:  "u=rwX,g=rwXs,o=rX"
      with_items:
        - "{{ blossom_install_path }}"
        - "{{ blossom_backup_path  }}"
        - "{{ blossom_site_home    }}"
        - "/var/log/cron"

    - name: "Extract release"
      ansible.builtin.unarchive:
        src:  "{{ blossom_archive_path }}"
        dest: "{{ blossom_install_path }}"
        owner: 'www-data'
        group: 'staff'

    - name: "Apache configuration"
      ansible.builtin.template:
        src:  "apache.conf"
        dest: "/etc/apache2/sites-enabled/conf.d/blossom.conf"
      notify: "apache_restart"

    - name: "Install CRON"
      ansible.builtin.template:
        src:  "cron.sh"
        dest: "/etc/cron.daily/backup.d/blossom"
        mode: "0755"

    - name: "Install site_config"
      ansible.builtin.template:
        src:  "site_config.j2"
        dest: "{{ blossom_site_home }}/site_config.php"

    - name: 'Update directory permissions'
      ansible.builtin.file:
        path: "{{ item }}"
        recurse: 'yes'
        mode:  'u=rwX,g=rwX,o=rX'
        owner: 'www-data'
        group: 'staff'
      with_items:
        - "{{ blossom_install_path }}"
        - "{{ blossom_backup_path  }}"
        - "{{ blossom_site_home    }}"
...
