<?php
/**
 * @copyright Copyright (C) 2006 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
 */
?>
<head>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<link rel="SHORTCUT ICON" href="/favicon.ico" />
	<style type="text/css" media="screen">
		@import url("/skins/default/skin.css");
	</style>
	<style type="text/css" media="print">@import url("/skins/default/print.css");</style>
	<title>New Application - City of Bloomington, Indiana</title>
</head>
<body>
<div id="banner">
	<div id="application_name"><a href="<?php echo BASE_URL; ?>">New Application</a></div>
	<div id="location_name">City of Bloomington, Indiana</div>
	<div id="navigation"></div>
</div>